baseURL = "https://jay.patel.org.in/"
languageCode = "en-us"
title = "Jay Patel"

# theme = "ananke"
# MetaDataFormat = "yaml"
# DefaultContentLanguage = "en"
# SectionPagesMenu = "main"
# Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
# googleAnalytics = ""
# enableRobotsTXT = true
#
# [sitemap]
#   changefreq = "monthly"
#   priority = 0.5
#   filename = "sitemap.xml"
#
# [params]
#   favicon = ""
#   description = "Jay's Personal Blog"
#   facebook = ""
#   twitter = "https://twitter.com/jayisms"
#   instagram = ""
#   youtube = ""
#   github = "https://github.com/jayp"
#   gitlab = ""
#   linkedin = "https://linkedin.com/in/jayisms"
#   mastodon = ""
#   slack = ""
#   stackoverflow = ""
#   # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
#   background_color_class = "bg-orange"
#   featured_image = "/images/gohugo-default-sample-hero-image.jpg"
#   recent_posts_number = 4

theme = "hyde-hyde"
[taxonomies]
   tag = "tags"
## Site Settings
[params]
    # author = "Jay A. Patel"
    # description = "..."
    authorimage = "/img/hugo.png"
    dateformat = "Jan 2, 2006"
[params.social]
	twitter = "jayisms"
	github = "jayp"
	linkedin = "jayisms"
## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
